spring:
  application:
    # Some Spring Cloud components use the DiscoveryClient in order to obtain info about the local
    # service instance. For this to work you need to align the service name with the
    # spring.application.name property.
    name: kubernetes-core
